---
title: "Testing And Development"
author: "Priyansh Srivastava"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
loader <- function(){
    suppressPackageStartupMessages(source("old_maSigPro/get.siggenes_test.R"))
    suppressPackageStartupMessages(source("old_maSigPro/average.rows_test.R"))
}
suppressPackageStartupMessages(library(maSigPro))
data(data.abiotic)
data(edesign.abiotic)
```


```{r}
head(data.abiotic)
head(edesign.abiotic)
```

```{r}
gc <- capture.output(design <- make.design.matrix(edesign.abiotic, degree = 2))
gc <- capture.output(fit <- p.vector(data.abiotic, design, Q = 0.05, MT.adjust = "BH", min.obs = 20))
gc <- capture.output(tstep <- T.fit(fit, step.method = "backward", alfa = 0.05))
```

```{r}
tstep2 <- readRDS("../benchMarking_Compression/Automated/ScMaSigProTstep/length_100_Sum_poly_2_minEx_10_K_1_bulkSumTstep.RDS")
colnames(tstep2$dis)

dis <- tstep2$dis
edesign <- tstep2$edesign
groups.vector <- tstep2$groups.vector
indep <- strsplit(colnames(dis)[grep("x", colnames(dis))[1]], "x")[[1]][1] # Selecting the time

# Selecting P-Values with higher r-sqaure
sig.pvalues <- tstep2$sol[which(tstep2$sol[, 2] > 0.7), ]

# Selecting counts with higher r-sqaure
sig.profiles <- tstep2$sig.profiles[which(tstep2$sol[, 2] > 0.7), ]

# Extraction of the Beta estimates
coefficients <- tstep2$coefficients[which(tstep2$sol[,2] > 0.7), ]

# Extraction of the Group Coefficients
group.coeffs <- tstep2$group.coeffs[which(tstep2$sol[, 2] > 0.7), ]

if (vars == "all") {
    sigs <- sig.profiles
    summary <- rownames(sig.profiles)
    coeffs <- coefficients
    gc <- group.coeffs
    ps <- sig.pvalues
    sig.genes <- list(sigs, coeffs, gc, ps, nrow(sig.profiles), edesign, groups.vector)
    names(sig.genes) <- c("sig.profiles", "coefficients",
                          "group.coeffs", "sig.pvalues", "g", "edesign",
                          "groups.vector")
}

else stop("invalid vars value, must be one of: all, each, groups")
sig.genes.test <- sig.genes
```

```{r}
#Extaction
loader()
sigs <- get.siggenes(tstep2, rsq = 0.7, vars = "groups")

suma2Venn(sigs$summary[, c(1:2)])


loader()
group.sig.test <- get.siggenes_test(tstep2, rsq = 0.7, vars = "groups", significant.intercept = "none")

apply(group.sig.test[c(1:8),], 1, function(x){
    print(!is.na(x))
    print(any(!is.na(x)))
    
    })

```